"use client";
import { useEffect, useState } from "react";
import Script from "next/script";
import { getMetaPixelScript, trackMetaEvent } from "@/lib/meta-pixel";
import { medicosConfig } from "../config";

export default function MedicosGracias() {
  const [valid, setValid] = useState<boolean | null>(null);
  useEffect(() => { fetch("/api/medicos/consume", { method: "POST" }).then(async (r) => { const result = await r.json() as { ok?: boolean; registrationId?: string }; if (r.ok && result.ok && result.registrationId) { setValid(true); const key = `cefin_medicos_complete_${result.registrationId}`; if (!sessionStorage.getItem(key)) { trackMetaEvent("CompleteRegistration", { content_name: medicosConfig.eventName, content_category: "Curso gratuito", eventID: result.registrationId }); sessionStorage.setItem(key, "1"); } } else setValid(false); }).catch(() => setValid(false)); }, []);
  if (valid === null) return <main className="medicos-result"><p>Validando tu registro…</p></main>;
  if (!valid) return <main className="medicos-result"><p className="medicos-section-label">REGISTRO NO ENCONTRADO</p><h1>Este acceso ya expiró</h1><a href="/landings/medicos">Volver al registro</a><style jsx global>{resultStyles}</style></main>;
  return <><Script id="meta-pixel-medicos-gracias" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: getMetaPixelScript(undefined, { trackPageView: false }) }} /><main className="medicos-result"><p className="medicos-section-label">PASO 2 DE 2 · NO CIERRES ESTA PÁGINA</p><h1>Solo falta entrar al grupo de WhatsApp</h1><p>Tus datos ya fueron guardados correctamente. Entra ahora al grupo oficial para completar tu acceso y recibir ahí los avisos e información del entrenamiento.</p><p className="medicos-note">Cuando se abra WhatsApp, todavía deberás tocar “Unirme al grupo”.</p><a className="medicos-cta" href="/landings/medicos/unirse-whatsapp">ENTRAR AL GRUPO OFICIAL</a><style jsx global>{resultStyles}</style></main></>;
}
const resultStyles = `.medicos-result{min-height:100svh;background:#050505;color:#fff;display:flex;flex-direction:column;justify-content:center;align-items:flex-start;gap:20px;padding:28px;max-width:820px;margin:auto;font-family:Arial,sans-serif}.medicos-result h1{font-family:Impact,'Arial Narrow',sans-serif;text-transform:uppercase;font-size:clamp(46px,8vw,96px);line-height:.92;margin:0}.medicos-result p:not(.medicos-section-label):not(.medicos-note){color:#d3d7ce;font-size:18px;line-height:1.6}.medicos-result .medicos-section-label{color:#c5ceae;font-size:11px;font-weight:800;letter-spacing:.18em}.medicos-result .medicos-note{color:#eea05a;font-weight:700}.medicos-result a:not(.medicos-cta){color:#eea05a}.medicos-result .medicos-cta{display:inline-flex;align-items:center;min-height:54px;padding:15px 22px;background:#ee8b32;color:#17100a;text-decoration:none;font-size:13px;font-weight:900;letter-spacing:.07em}`;
