import "server-only";

import type { HotmartOfferConfig } from "@/lib/hotmart/types";

const pendingProductUcode = "";

export const hotmartOffers = {
  academiaContabilidadInscripcion: {
    route: "/landings/academia-contabilidad/inscripcion",
    productUcode: pendingProductUcode,
    offerCode: "ciu6d3oe",
    fallbackPrice: 1987,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  academiaContabilidadLive: {
    route: "/landings/academia-contabilidad/live",
    productUcode: pendingProductUcode,
    offerCode: "9ho393qq",
    fallbackPrice: 3387,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  asesorFiscalPfInscripcion: {
    route: "/landings/asesor-fiscal-pf/inscripcion",
    productUcode: pendingProductUcode,
    offerCode: "2fonqwf3",
    fallbackPrice: 4787,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  auxiliarContableRetargeting: {
    route: "/landings/auxiliar-contable/retargeting",
    productUcode: pendingProductUcode,
    offerCode: "wnp9zod8",
    fallbackPrice: 4387,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  constructorasInscripcion: {
    route: "/landings/constructoras/inscripcion",
    productUcode: pendingProductUcode,
    offerCode: "hpfi29f1",
    fallbackPrice: 4787,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  estrategaFiscalInscripcion: {
    route: "/landings/de-cero-a-estratega-fiscal/inscripcion",
    productUcode: pendingProductUcode,
    offerCode: "hs9wp3t0",
    fallbackPrice: 0,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  despiertaPotencialInscripcion: {
    route: "/landings/despierta-tu-potencial-contable/inscripcion",
    productUcode: pendingProductUcode,
    offerCode: "kmo127nh",
    fallbackPrice: 4787,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  iaContadoresEcosistema: {
    route: "/landings/master-ia/ecosistema",
    productUcode: pendingProductUcode,
    offerCode: "mxynkrmw",
    fallbackPrice: 12387,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  iaContadoresInscripcion: {
    route: "/landings/master-ia/inscripcion",
    productUcode: "f0d5a6ed-2de1-4f2b-91a2-b00b444c7e28",
    offerCode: "row94rfv",
    fallbackPrice: 587,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  iaContadoresRetargeting: {
    route: "/landings/master-ia/retargeting",
    productUcode: pendingProductUcode,
    offerCode: "7l62yrr2",
    fallbackPrice: 3387,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  cuentasContables: {
    route: "/landings/low-tickets/cuentas-contables",
    productUcode: pendingProductUcode,
    offerCode: "rf1ez41t",
    fallbackPrice: 297,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  honorariosContables: {
    route: "/landings/low-tickets/honorarios-contables",
    productUcode: pendingProductUcode,
    offerCode: "y8s212iw",
    fallbackPrice: 297,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  primerosClientes: {
    route: "/landings/low-tickets/primeros-clientes",
    productUcode: pendingProductUcode,
    offerCode: "60uw7x37",
    fallbackPrice: 297,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  serviciosContables: {
    route: "/landings/low-tickets/servicios-contables",
    productUcode: pendingProductUcode,
    offerCode: "lgv68uq8",
    fallbackPrice: 197,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  nifInscripcion: {
    route: "/landings/nif/inscripcion",
    productUcode: pendingProductUcode,
    offerCode: "57a4x11n",
    fallbackPrice: 9987,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  nifTaller: {
    route: "/landings/nif/taller",
    productUcode: pendingProductUcode,
    offerCode: "anbe55e7",
    fallbackPrice: 587,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
  nominaInscripcion: {
    route: "/landings/nomina/inscripcion",
    productUcode: "0329ef53-39e9-4cfb-abdf-6f3b0e1304fa",
    offerCode: "rk750909",
    fallbackPrice: 5987,
    currency: "MXN",
    locale: "es-MX",
    enabled: true,
  },
  restaurantesInscripcion: {
    route: "/landings/restaurantes/inscripcion",
    productUcode: pendingProductUcode,
    offerCode: "",
    fallbackPrice: 3687,
    currency: "MXN",
    locale: "es-MX",
    enabled: false,
  },
} as const satisfies Record<string, HotmartOfferConfig>;

export type HotmartOfferKey = keyof typeof hotmartOffers;

export function getHotmartOfferConfig(key: HotmartOfferKey): HotmartOfferConfig {
  return hotmartOffers[key];
}
