import Image from "next/image";
import {
  CheckoutLink,
  RestaurantesInscripcionAnalytics,
} from "./restaurantes-inscripcion-tracking";

const PRICE_LABEL = "$4,787 MXN";

const pains = [
  "No sabes qué preguntar en la primera reunión.", "Revisas información sin un orden claro.",
  "Te preocupa pasar por alto un riesgo fiscal.", "El cliente espera respuestas específicas.",
  "Terminas asesorando como a cualquier otro negocio.", "Te cuesta justificar el valor de tu servicio.",
  "Quieres especializarte, pero no sabes por dónde empezar.", "Sientes que necesitas más criterio para atenderlos.",
];
const outcomes = [
  ["01", "Entender el negocio", "Identifica cómo funciona un restaurante y qué lo hace distinto fiscalmente."],
  ["02", "Hacer mejores preguntas", "Llega a la primera conversación con una guía para obtener información útil."],
  ["03", "Detectar puntos críticos", "Ordena la revisión de ingresos, gastos, personal, plataformas y operación."],
  ["04", "Construir tu diagnóstico", "Pasa de revisar documentos sueltos a analizar el negocio como un sistema."],
  ["05", "Explicar con seguridad", "Comunica tus recomendaciones de forma clara y profesional."],
  ["06", "Evitar errores comunes", "Reconoce los focos rojos que suelen aparecer en negocios de alimentos."],
  ["07", "Diferenciar tu servicio", "Deja de competir solo por precio y desarrolla una asesoría especializada."],
  ["08", "Aplicarlo con clientes", "Lleva el método a restaurantes, cafeterías y negocios de comida."],
];
const program = [
  { day: "Módulo 1", title: "Cómo funciona un restaurante", bullets: ["La operación detrás del negocio.", "Modelos de restaurante y cafetería.", "Dónde se genera el ingreso y el gasto.", "Qué información pedir desde el inicio."], key: "No puedes asesorar bien lo que todavía no comprendes." },
  { day: "Módulo 2", title: "Los puntos fiscales que debes revisar", bullets: ["Ingresos, gastos y comprobación.", "Personal, propinas y pagos.", "Plataformas de entrega y medios de cobro.", "Preguntas que revelan riesgos."], key: "La calidad de tu asesoría empieza con la calidad de tu revisión." },
  { day: "Módulo 3", title: "Tu método de diagnóstico", bullets: ["Cómo ordenar la información del cliente.", "Checklist para una revisión inicial.", "Qué priorizar y qué dejar para después.", "Cómo documentar tus hallazgos."], key: "Pasa de la intuición a una estructura que puedas repetir." },
  { day: "Módulo 4", title: "Asesoría que genera valor", bullets: ["Cómo presentar tus recomendaciones.", "Cómo hablar de riesgos sin alarmar.", "Cómo delimitar tu alcance profesional.", "Cómo convertir criterio en una propuesta."], key: "Tu especialización se nota cuando el cliente entiende el valor de tu trabajo." },
];
const audience = ["Eres contador o asesor fiscal.", "Quieres atender restaurantes o cafeterías.", "Te cuesta saber qué revisar primero.", "Quieres trabajar con una metodología práctica.", "Buscas especializar tu servicio.", "Quieres cobrar con más seguridad.", "Te interesa dar una asesoría más estratégica.", "Quieres dejar de improvisar con cada cliente."];
const includes = ["Formación especializada en restaurantes.", "Método de revisión paso a paso.", "Ejemplos de negocios de alimentos.", "Checklist de diagnóstico inicial.", "Guía de preguntas para el cliente.", "Materiales prácticos de trabajo.", "Recomendaciones para presentar tu servicio.", "Acceso a la ruta completa del programa."];
const faqs = [
  ["¿Necesito experiencia atendiendo restaurantes?", "No. El programa parte de la operación del negocio y te ayuda a construir una base clara para comenzar a asesorarlos."],
  ["¿Esto sustituye mi criterio profesional?", "No. La formación te da estructura y contexto para que puedas aplicar tu propio criterio con mayor seguridad."],
  ["¿Me sirve si ya tengo clientes de comida?", "Sí. Puedes usar el método para ordenar la información y detectar oportunidades de mejora en tu asesoría actual."],
  ["¿Solo aplica para restaurantes grandes?", "No. Los principios pueden aplicarse a restaurantes, cafeterías, cocinas económicas y otros negocios de alimentos."],
  ["¿Qué incluye la inscripción?", "El acceso a la formación, los materiales prácticos y la ruta de trabajo que se indique en la oferta vigente."],
];

export default function RestaurantesInscripcionPage() {
  return <>
    <RestaurantesInscripcionAnalytics />
    <main className="overflow-x-hidden bg-[#120906] text-white">
    <section className="relative isolate min-h-svh overflow-hidden">
      <div className="absolute inset-0 -z-30 bg-[radial-gradient(circle_at_78%_20%,rgba(234,88,12,.25),transparent_28%),radial-gradient(circle_at_18%_18%,rgba(251,146,60,.13),transparent_28%),linear-gradient(120deg,#090504_0%,#241006_52%,#120906_100%)]" />
    <div className="restaurant-inscripcion-grid absolute inset-0 -z-20 opacity-[0.14]" />
      <div className="mx-auto flex min-h-svh max-w-[1240px] flex-col px-5 pb-8 pt-6 sm:px-8 lg:px-10">
        <header className="flex items-center justify-between"><div className="inline-flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center border border-orange-300/30 bg-orange-300/10 text-sm font-black text-orange-200">C</span><div><p className="text-lg font-black">CEFIN</p><p className="hidden text-[10px] uppercase tracking-[0.18em] text-orange-100/50 sm:block">Formación fiscal especializada</p></div></div><CheckoutLink className="inline-flex min-h-11 items-center bg-orange-500 px-5 text-xs font-black uppercase text-white shadow-[0_0_28px_rgba(234,88,12,.22)] transition hover:-translate-y-0.5 hover:bg-orange-400">Inscribirme ya</CheckoutLink></header>
        <div className="grid flex-1 items-center gap-10 py-10 lg:grid-cols-[1.05fr_.95fr]"><div><p className="inline-flex border border-orange-300/25 bg-orange-300/10 px-4 py-2 text-xs font-black uppercase tracking-[0.22em] text-orange-200">Programa para contadores y asesores fiscales</p><h1 className="mt-6 max-w-4xl text-[clamp(3rem,7vw,6.4rem)] font-black uppercase leading-[0.88] tracking-[-0.06em]">Convierte tu conocimiento fiscal en una <span className="block bg-gradient-to-r from-orange-300 via-orange-500 to-red-400 bg-clip-text text-transparent">asesoría especializada</span><span className="block">para restaurantes</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-orange-50/75 sm:text-xl">Aprende a revisar, preguntar y atender restaurantes, cafeterías y negocios de comida con una estructura clara, práctica y profesional.</p><div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-center"><p className="border border-orange-300/35 bg-orange-300/10 px-6 py-4 text-2xl font-black text-orange-200">{PRICE_LABEL}</p><CheckoutLink className="inline-flex min-h-16 items-center justify-center bg-orange-500 px-8 text-base font-black uppercase text-white shadow-[0_20px_60px_rgba(234,88,12,.25)] transition hover:-translate-y-1 hover:bg-orange-400">Inscribirme ya <span className="ml-4 text-2xl">→</span></CheckoutLink></div><p className="mt-4 text-sm font-bold uppercase tracking-[0.14em] text-orange-100/45">Pago seguro a través de Hotmart.</p></div><div className="relative"><div className="absolute -inset-5 bg-gradient-to-br from-orange-400/15 via-red-500/10 to-amber-300/20 blur-2xl" /><div className="relative min-h-[520px] overflow-hidden border border-white/10 bg-white/[0.06] backdrop-blur-xl"><div className="restaurant-inscripcion-grid absolute inset-0 opacity-[0.18]" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_18%,rgba(251,146,60,.22),transparent_28%),linear-gradient(to_bottom,rgba(18,9,6,.08),#120906_92%)]" /><div className="absolute left-5 top-5 z-20 border border-orange-300/30 bg-[#120906]/80 px-4 py-3 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-300">Asesor Fiscal</p><p className="mt-1 text-sm font-bold text-white">Restaurantes y negocios de comida</p></div><div className="absolute bottom-6 right-5 z-20 max-w-[250px] border border-orange-300/30 bg-orange-500 px-5 py-4 text-white shadow-[0_20px_70px_rgba(234,88,12,.25)]"><p className="text-xs font-black uppercase tracking-[0.18em] text-white/65">CEFIN</p><p className="mt-1 text-2xl font-black uppercase leading-none">Más criterio. Más valor.</p></div><div className="absolute bottom-0 left-1/2 z-10 h-full w-full -translate-x-1/2"><Image src="/restaurantes/alfredo-restaurantes.png" alt="Mtro. Alfredo Cobos" priority unoptimized className="h-full w-full object-contain object-bottom" /></div></div></div></div>
      </div>
    </section>

    <section className="bg-[#120906] px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1160px]"><div className="max-w-3xl"><p className="eyebrow">El problema</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-5xl">¿Sientes que cada restaurante te exige empezar desde cero?</h2><p className="mt-5 text-lg leading-relaxed text-orange-50/55">El problema no es que te falte capacidad. Es que necesitas una estructura específica para comprender y revisar este tipo de negocios.</p></div><div className="mt-12 grid gap-px bg-orange-300/15 sm:grid-cols-2 lg:grid-cols-4">{pains.map((pain) => <div key={pain} className="bg-[#241006] p-6"><p className="font-bold text-orange-50/75">{pain}</p></div>)}</div></div></section>

    <section className="bg-[#241006] px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto grid max-w-[1160px] gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">El reencuadre</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-5xl">Un restaurante no necesita una asesoría genérica.</h2><p className="mt-5 text-lg leading-relaxed text-orange-50/70">Necesita a alguien que entienda su operación, sepa qué revisar y pueda explicar sus recomendaciones con seguridad. Esta formación te ayuda a construir ese criterio.</p></div><div className="grid gap-px bg-orange-300/15">{[["Tú puedes ordenar la información", "Pero el negocio tiene una operación particular"], ["Tú puedes revisar sus comprobantes", "Pero debes comprender qué hay detrás de ellos"], ["Tú puedes dar recomendaciones", "Pero necesitas sustentarlas con criterio"]].map(([left, right]) => <div key={left} className="grid gap-px bg-orange-300/15 sm:grid-cols-2"><div className="bg-[#170c07] p-5 font-bold text-orange-100">{left}</div><div className="bg-[#170c07] p-5 font-bold text-amber-200">{right}</div></div>)}</div></div></section>

    <section className="bg-[#120906] px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1240px]"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow">Lo que lograrás</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-5xl">Podrás atender restaurantes con más orden y seguridad.</h2></div><div className="mt-12 grid border-l border-t border-white/10 sm:grid-cols-2 lg:grid-cols-4">{outcomes.map(([number, title, text]) => <article key={number} className="border-b border-r border-white/10 p-6 transition hover:bg-white/[.05]"><p className="text-sm font-black text-orange-300">{number}</p><h3 className="mt-6 text-xl font-black uppercase text-white">{title}</h3><p className="mt-3 text-sm leading-relaxed text-orange-50/50">{text}</p></article>)}</div></div></section>

    <section className="relative overflow-hidden bg-orange-500 px-5 py-12 text-white sm:px-8 lg:px-10"><div className="restaurant-inscripcion-grid absolute inset-0 opacity-20" /><div className="relative mx-auto flex max-w-[1160px] flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.24em] text-white/65">Ya viste lo que puede cambiar</p><h2 className="mt-3 text-4xl font-black uppercase leading-tight sm:text-5xl">Compra una estructura para dejar de improvisar con cada cliente.</h2><p className="mt-4 max-w-2xl text-lg font-semibold leading-relaxed text-white/75">Aprende a convertir tu conocimiento fiscal en una asesoría más clara, especializada y valiosa.</p></div><div className="shrink-0 border-2 border-[#170c07] bg-[#170c07] p-2"><CheckoutLink className="inline-flex min-h-16 w-full items-center justify-center bg-white px-8 text-base font-black uppercase text-[#170c07] transition hover:-translate-y-1 hover:bg-orange-50 sm:w-auto">Inscribirme ya <span className="ml-3 text-2xl">→</span></CheckoutLink><p className="mt-3 text-center text-sm font-black uppercase text-orange-200">{PRICE_LABEL} · Programa especializado</p></div></div></section>

    <section className="bg-[#241006] px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1160px]"><div className="max-w-3xl"><p className="eyebrow">Programa especializado</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-5xl">Esto es lo que trabajarás durante la formación.</h2></div><div className="mt-12 space-y-5">{program.map((item) => <article key={item.day} className="grid gap-6 border border-white/10 bg-white/[.04] p-6 lg:grid-cols-[170px_1fr]"><div><p className="text-sm font-black uppercase tracking-[.24em] text-orange-300">{item.day}</p><h3 className="mt-3 text-2xl font-black uppercase text-white">{item.title}</h3></div><div><ul className="grid gap-3 text-orange-50/70 sm:grid-cols-2">{item.bullets.map((bullet) => <li key={bullet}>• {bullet}</li>)}</ul><p className="mt-5 border-l-4 border-orange-300 bg-orange-300/10 p-4 font-bold text-orange-100">{item.key}</p></div></article>)}</div><div className="mt-10 flex flex-col items-start justify-between gap-5 border border-orange-300/25 bg-orange-300/10 p-6 sm:flex-row sm:items-center"><div><p className="text-sm font-black uppercase tracking-[.18em] text-orange-300">Siguiente grupo</p><p className="mt-2 text-2xl font-black uppercase text-white">Aparta tu acceso ahora.</p></div><CheckoutLink className="inline-flex min-h-14 w-full items-center justify-center bg-orange-500 px-7 text-sm font-black uppercase text-white transition hover:bg-orange-400 sm:w-auto">Inscribirme ya <span className="ml-3 text-xl">→</span></CheckoutLink></div></div></section>

    <section className="bg-[#120906] px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto grid max-w-[1160px] gap-10 lg:grid-cols-2"><div><p className="eyebrow">Esto es para ti si...</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-5xl">Quieres trabajar mejor sin perder tu criterio.</h2><div className="mt-8 space-y-4">{audience.map((item) => <p key={item} className="border border-white/10 bg-white/[.04] p-4 font-bold text-orange-50/70">✓ {item}</p>)}</div></div><div className="border border-red-400/25 bg-red-500/10 p-8"><p className="text-sm font-black uppercase tracking-[.2em] text-red-200">Esto no es para ti si...</p><p className="mt-5 text-3xl font-black leading-tight">Buscas una receta para asesorar sin revisar, sin comprender la operación o sin aplicar tu propio criterio profesional.</p></div></div></section>

    <section className="bg-[#241006] px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1160px]"><p className="eyebrow text-center">Qué incluye</p><h2 className="mt-4 text-center text-4xl font-black uppercase sm:text-5xl">Tu acceso al programa incluye:</h2><div className="mt-12 grid border-l border-t border-white/10 sm:grid-cols-2 lg:grid-cols-4">{includes.map((item) => <div key={item} className="border-b border-r border-white/10 p-6"><p className="font-bold text-orange-50/70">{item}</p></div>)}</div><div className="mt-10 text-center"><CheckoutLink className="inline-flex min-h-14 items-center justify-center bg-orange-500 px-8 text-sm font-black uppercase text-white transition hover:bg-orange-400">Inscribirme ya <span className="ml-3 text-xl">→</span></CheckoutLink></div></div></section>

    <section className="bg-[#120906] px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-[900px]"><p className="eyebrow text-center">Tal vez estás pensando...</p><h2 className="mt-4 text-center text-4xl font-black uppercase sm:text-5xl">Preguntas frecuentes</h2><div className="mt-10 border-t border-white/10">{faqs.map(([question, answer]) => <details key={question} className="group border-b border-white/10 py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-black">{question}<span className="text-2xl text-orange-300 transition group-open:rotate-45">+</span></summary><p className="max-w-3xl pt-4 leading-relaxed text-orange-50/55">{answer}</p></details>)}</div></div></section>

    <section id="comprar" className="relative overflow-hidden bg-[#241006] px-5 py-20 sm:px-8 lg:px-10"><div className="restaurant-inscripcion-grid absolute inset-0 opacity-[.1]" /><div className="relative mx-auto grid max-w-[1120px] gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="restaurant-inscripcion-eyebrow">Cierre de venta</p><h2 className="mt-4 text-4xl font-black uppercase sm:text-6xl">El próximo restaurante que llegue a tu despacho puede encontrarte preparado.</h2><p className="mt-5 max-w-2xl text-lg leading-relaxed text-orange-50/65">No necesitas memorizarlo todo. Necesitas usar una estructura, hacer mejores preguntas y aplicar tu criterio con más claridad.</p></div><div className="border border-orange-300/25 bg-[#120906]/70 p-7 text-center"><p className="text-sm font-black uppercase tracking-[.22em] text-orange-300">Asesor Fiscal de Restaurantes</p><p className="mt-3 text-5xl font-black text-orange-200">{PRICE_LABEL}</p><CheckoutLink className="mt-7 inline-flex min-h-16 w-full items-center justify-center bg-orange-500 px-7 text-base font-black uppercase text-white transition hover:-translate-y-1 hover:bg-orange-400">Inscribirme ya <span className="ml-4 text-2xl">→</span></CheckoutLink><p className="mt-4 text-sm text-orange-50/40">Pago seguro a través de Hotmart.</p></div></div></section>
    <footer className="border-t border-white/10 bg-[#090504] px-5 py-7 text-center text-sm text-orange-50/40">CEFIN · Formación fiscal especializada para contadores y asesores</footer>
  </main>
  </>;
}
